version: "3"
services:

    elasticsearch:
      image: ${IMAGE_NAME}
      volumes:
        - './data:/usr/share/elasticsearch/data'
      container_name: ${CONTAINER_NAME}
      ports:
        - "9200:9200"
        - "9300:9300"
      networks:
        - database_app
      environment:
        - discovery.type=single-node

networks: 
    database_app:
        external: true