version: "3"
services:

    elasticsearch:
      build:
        context: .
        dockerfile: ESDockerfile
        args:
          - ES_VERSION=${ES_VERSION}

      volumes:
        - './data:/usr/share/elasticsearch/data'
        - './elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml'
      container_name: ${ES_CONTAINER_NAME}
      ports:
        - "9200:9200"
        - "9300:9300"
      networks:
        - database_app

    kibana:
      image: kibana:${KIBANA_VERSION}
      ports:
        - "5601:5601"
      networks:
        - database_app
      environment:
        - 'ELASTICSEARCH_HOSTS=http://${ES_CONTAINER_NAME}:9200'

    head:
      build: .
      ports:
        - "9100:9100"
      networks:
        - database_app

networks: 
    database_app:
        external: true